<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_test_home' => [[], ['_controller' => 'App\\Controller\\TestController::home'], [], [['text', '/']], [], [], []],
    'app_test_me' => [[], ['_controller' => 'App\\Controller\\TestController::me'], [], [['text', '/me']], [], [], []],
    'App\Controller\TestController::home' => [[], ['_controller' => 'App\\Controller\\TestController::home'], [], [['text', '/']], [], [], []],
    'App\Controller\TestController::me' => [[], ['_controller' => 'App\\Controller\\TestController::me'], [], [['text', '/me']], [], [], []],
];
